apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: burrzinga-accounting
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-appstudio-appdata/accounting-gTo1P-let-hurt
    path:  components/java-springboot-hello-qnbe/overlays/development/
    targetRevision: HEAD
  destination:
    namespace: burrzinga-tenant
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true